### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by smu1990** [Cosium/bitbucket-to-gerrit#1]
Below mentioned URI is not working.
https://registry.npmjs.org/bitbucket-to-gerrit
Hence i am not able to run npx bitbucket-to-gerrit --help

**Comment by reda-alaoui** [comment]
Sorry for that. I guess the deployment was made on a private repository.
I just deployed 1.1.5 release to the public registry.
It should work now :)

**Comment by reda-alaoui** [comment]
https://www.npmjs.com/package/bitbucket-to-gerrit
